test_clickstream = [
    ('page', 'a', '/'),
    ('page', 'b', '/cheese'),
    ('pixel', 'a'),
    ('page', 'a', '/potatoes'),
    ('page', 'a', '/potatoes/sweet'),
    ('pixel', 'b'),
    ('page', 'a', '/potatoes/russet'),
    ('page', 'b', '/cheese/parmesan'),
    ('page', 'c', '/fruit/apples'),
    ('page', 'b', '/cart'),
    ('goal', 'b', 'add to cart', ''),
    ('page', 'c', '/fruit/bananas'),
    ('split', 'b', 'red checkout form'),
    ('page', 'b', '/checkout'),
    ('goal', 'b', 'began checkout', ''),
    ('page', 'a', '/cart'),
    ('goal', 'a', 'add to cart', ''),
    ('pixel', 'c'),
    ('page', 'a', '/cheese/gouda'),
    ('page', 'a', '/cheese'),
    ('page', 'b', '/cheese'),
    ('page', 'd', '/'),
    ('pixel', 'd'),
    ('split', 'b', 'red checkout form'),
    ('page', 'd', '/cheese'),
    ('page', 'd', '/cheese/gruyere'),
    ('page', 'b', '/checkout/complete'),
    ('goal', 'b', 'completed checkout', 31.78),
    ('page', 'c', '/'),
    ('page', 'd', '/cart'),
    ('goal', 'd', 'add to cart', ''),
    ('page', 'd', '/checkout'),
    ('goal', 'd', 'began checkout', ''),
    ('page', 'a', '/account'),
    ('page', 'e', '/fruit'),
    ('pixel', 'e'),
    ('page', 'd', '/checkout/complete'),
    ('goal', 'd', 'completed checkout', 64.99),
    ('page', 'e', '/fruit/pineapples'),
    ('page', 'e', '/fruit/cherries'),
    ('page', 'e', '/fruit/pears'),
    ('page', 'e', '/cart'),
    ('goal', 'e', 'add to cart', ''),
    ('page', 'e', '/checkout'),
    ('goal', 'e', 'began checkout', ''),
    ('page', 'd', '/account'),
    ('page', 'd', '/'),
    ('page', 'e', '/checkout/complete'),
    ('goal', 'e', 'completed checkout', 11.42),
    ('page', 'b', '/fruit'),
]
