test_clickstream = [
    ('page', 'a', '/'),
    ('page', 'b', '/cheese'),
    ('pixel', 'a'),
    ('page', 'a', '/potatoes'),
    ('page', 'a', '/potatoes/sweet'),
    ('pixel', 'b'),
    ('page', 'a', '/potatoes/russet'),
    ('page', 'b', '/cheese/parmesan'),
    ('page', 'c', '/fruit/apples'),
    ('page', 'b', '/cart'),
    ('goal', 'b', 'add to cart', ''),
    ('page', 'c', '/fruit/bananas'),
    ('split', 'b', 'red checkout form'),
    ('page', 'b', '/checkout'),
    ('goal', 'b', 'began checkout', ''),
    ('page', 'a', '/cart'),
    ('goal', 'a', 'add to cart', ''),
    ('pixel', 'c'),
    ('page', 'a', '/cheese/gouda'),
    ('page', 'a', '/cheese'),
    ('page', 'b', '/cheese'),
    ('split', 'b', 'red checkout form'),
    ('page', 'b', '/checkout/complete'),
    ('goal', 'b', 'completed checkout', 31.78),
    ('page', 'c', '/'),
]
