test_clickstream = [
    ('page', 'a', '/'),
    ('page', 'b', '/cheese'),
    ('pixel', 'a'),
    ('page', 'a', '/potatoes'),
    ('page', 'a', '/potatoes/sweet'),
    ('pixel', 'b'),
    ('page', 'a', '/potatoes/russet'),
    ('page', 'b', '/cheese/parmesan'),
    ('page', 'c', '/fruit/apples'),
    ('page', 'b', '/cart'),
    ('goal', 'b', 'add to cart'),
    ('page', 'c', '/fruit/bananas'),
    ('page', 'b', '/checkout'),
    ('goal', 'b', 'began checkout'),
    ('page', 'a', '/cart'),
    ('goal', 'a', 'add to cart'),
    ('pixel', 'c'),
    ('page', 'a', '/cheese/gouda'),
    ('page', 'a', '/cheese'),
    ('page', 'b', '/cheese'),
    ('page', 'b', '/checkout/complete'),
    ('goal', 'b', 'completed checkout'),
    ('page', 'c', '/'),
]
